@startuml "CDA Bet Class Diagram"
hide empty members
skinparam linetype ortho
caption CDA Bet Class Diagram
footer Joël L & Bertrand C
header Last updated 04/11/2020
title CDA Bet

namespace CdaBet {
    ' TODO: complete the attributes, add the types and methods
    ' TODO: Manage payment type
    ' Abstract class for people to extend?
    class User {
        -gender
        -lastname
        -firstname
        -address
        -city
        -postcode
        -birthdate
        -phonenumber
        -email
        -password
        -active
        -verified
        -maximunWeeklyBet
    }

    class Country{
        -name
    }

    class TimeZone{
        -code
        -name
    }

    ' add protected
    class Wallet {
        -balance
        #credit()
        #debit()
        #history()
    }

    class Payment {
        -amount
        -date
        -transactionID
        -description
        +make()
    }

    class Sport {
        -name
        -description
    }

    ' Could be an enumeration?
    ' add Bool ifTeams
    class SportType {
        -name
        -description
        -Bool ifTeams
    }

    ' Abstract class for people to extend?
    class Competitor {
        -name
    }

    class Team {
        -name
        -description
    }

    ' Need for a class/markup between Team/Competitor and Event?
    class Event {
        -name
        -date
        -location
        -illustration
    }

    class Competition {
        -name
    }

    class Odds {
        -description
        -value
    }

    class OddsType {
    }

    class Bet {
        -amount
        -odds
        +make()
        +resolve()
    }

    class Order {
        -date
        -total
    }

    User "1" *-- "1" Wallet : has >
    User "1" -- "0..n" Country : has >
    User "1" -- "0..n" TimeZone : is in >
    Country "1..n" -- "0..n" TimeZone : is in >
    Wallet "0..n" *-- "1" Payment
    Sport "1..n" --o "0..n" SportType
    Competitor "0..n" --o "2..n" Team
    Competitor "1" --o "0..n" Country
    Team "1" --o "0..n" Country
    Odds "1" --o "0..n" OddsType
    (User, Odds) "1" *-- "1" Bet
    Event "0..1" --* "1..n" Competition
    Competition "0..1" --* "1..n" Competition
    Competition "1" -- "0..n" Sport
    Competition "1" -- "0..n" SportType
    Order "1" *-- "1" Payment
    Event "1..n" *-- "1" Odds
    Event "1" -- "0..n" Sport
    Event "1" -- "0..n" SportType
    Event "2..n" -- "0..n" Competitor
    Event "2..n" -- "0..n" Team
    Event "1" -- "0..n" Country
    Event "1" -- "0..n" TimeZone
    User "0..n" *-- "1" Order
    Order "1" *-- "1" Bet
    ' Ajouter lien pari-joueur
    ' Cacher le panier
    ' Gérer les remplaçants
}
@enduml

@startmindmap "CDA Bet Mind Map"
* CDA Bet
** Class
** Actions
*** Sign up
*** Sign in
*** Log out
*** Show user profile
*** Show bet history
*** Credit wallet
*** Debit wallet
*** Show transactions history
*** Show events by category
*** Show Bets
*** Make a bet
** Component
*** Symfony
*** PHPStan
@endmindmap