@startuml "CDA Bet Class Diagram"
hide empty members
skinparam linetype ortho
caption CDA Bet Class Diagram
footer Joël L & Bertrand C
header Last updated 04/11/2020
title CDA Bet

namespace CdaBet {
    ' TODO: check the attributes, the types and methods
    ' TODO: Manage payment type
    ' TODO: Abstract class for people to extend?
    ' TODO: Manage the results and win
    class User {
        -String gender
        -String lastname
        -String firstname
        -String address
        -String city
        -Int postcode
        -Date birthdate
        -Int phonenumber
        -String email
        -String password
        -Bool active
        -Bool verified
        -Float maximunWeeklyBet
    }

    class Country{
        -String name
    }

    class TimeZone{
        -String code
        -String name
    }

    ' add protected
    class Wallet {
        -Float balance
        #credit(balance)
        #debit(balance)
        #history()
    }

    class Payment {
        -Float amount
        -Date date
        -String transactionID
        -String description
        +make()
        +cancel(transactionID)
    }

    class Sport {
        -String name
        -String description
    }

    ' Could be an enumeration?
    ' add Bool ifTeams
    class SportType {
        -String name
        -String description
        -Bool ifTeams
    }

    ' Abstract class for people to extend?
    class Competitor {
        -String name
    }

    class Team {
        -Sting name
        -String description
    }

    ' Need for a class/markup between Team/Competitor and Event?
    class Event {
        -String name
        -Date date
        -String location
        -String illustration
        -Int Score
        -String whoWins
    }

    class Competition {
        -String name
    }

    class Odds {
        -String description
        -Float value
    }

    /' Unused class for now
    class OddsType {
    }
    '/

    class Bet {
        -Int amount
        -Float odds
        -Bool resolved
        +make()
        +resolve()
    }

    class Order {
        -Date date
        -Float total
    }

    User "1" *-- "1" Wallet : has >
    User "1" -- "0..n" Country : has >
    User "1" -- "0..n" TimeZone : is in >
    Country "1..n" -- "0..n" TimeZone : is in >
    Wallet "0..n" -- "1" Payment
    Sport "1..n" --o "0..n" SportType
    Competitor "0..n" --o "2..n" Team
    Competitor "1" --o "0..n" Country
    Team "1" --o "0..n" Country
    Odds "1" --o "0..n" OddsType
    (User, Odds) "1" *-- "1" Bet
    Event "0..1" --* "1..n" Competition
    Competition "0..1" --* "1..n" Competition
    Competition "1" -- "0..n" Sport
    Competition "1" -- "0..n" SportType
    Order "1" *-- "1" Payment
    Event "1..n" *-- "1" Odds
    Event "1" -- "0..n" Sport
    Event "1" -- "0..n" SportType
    Event "2..n" -- "0..n" Competitor
    Event "2..n" -- "0..n" Team
    Event "1" -- "0..n" Country
    Event "1" -- "0..n" TimeZone
    User "0..n" *-- "1" Order
    Order "1" *-- "1" Bet
    ' Ajouter lien pari-joueur
    ' Cacher le panier
    ' Gérer les remplaçants
}
@enduml

@startmindmap "CDA Bet Mind Map"
* CDA Bet
** Class
** Actions
*** Sign up
*** Sign in
*** Log out
*** Show user profile
*** Show bet history
*** Credit wallet
*** Debit wallet
*** Show transactions history
*** Show events by category
*** Show Bets
*** Make a bet
** Component
*** Symfony
*** PHPStan
@endmindmap