version: "3"
services:
  php74:
    build:
      context: docker/php74-xdebug
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - ./code:/app

  composer:
    restart: "no"
    image: composer
    command: install
    working_dir: /app
    volumes:
      - ./code:/app

  mysql:
    image: mysql:5.7
    container_name: appDatabase
    restart: always
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8060:80"
    environment:
      PMA_HOST: mysql

  traefik:
    image: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./docker/traefik/conf/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mailhog:
    image: "mailhog/mailhog"
