version: "3"
services:
  php:
    build:
      context: docker/php74-xdebug
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - ./code:/app
    restart: on-failure
    depends_on:
      - composer
      - db
      - mailhog

  composer:
    image: composer
    volumes:
      - ./code:/app
    command: ["install"]

  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    environment:
      PMA_ABSOLUTE_URI: http://phpmyadmin-parisportif1.docker.localhost/
    depends_on:
      - db

  traefik:
    image: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./docker/traefik/conf/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: on-failure
    depends_on:
      - php
      - phpmyadmin
      - mailhog

  mailhog:
    image: "mailhog/mailhog"
    restart: on-failure
