version: "3"

services:
  php:
    build:
      context: docker/php74-xdebug
      cache_from:
        - php:7.4-apache
    volumes:
      - ./code:/app
    restart: on-failure
    depends_on:
      - db
      - mailhog

  composer:
    image: composer
    volumes:
      - ./code:/app
      - .git:/.git

  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - db-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    environment:
      # Update in case of service name change
      PMA_ABSOLUTE_URI: http://phpmyadmin-parisportif1.docker.localhost/
    depends_on:
      - db

  traefik:
    image: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./docker/traefik/conf/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - php
      - phpmyadmin
      - mailhog

  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    volumes:
      - mail-volume:/maildir
    labels:
      - traefik.http.services.mailhog.loadbalancer.server.port=8025

volumes:
  db-volume:
  mail-volume: