version: "3"
services:
  php74:
    build:
      context: docker/php74-xdebug
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - ./code:/app
    restart: on-failure

  composer:
    image: composer
    command: install
    working_dir: /app
    volumes:
      - ./code:/app

  mysql:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - "8060:80"
    environment:
      PMA_HOST: mysql

  traefik:
    image: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./docker/traefik/conf/traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: on-failure

  mailhog:
    image: "mailhog/mailhog"
    restart: on-failure
