FROM php:7.4-apache

WORKDIR "/app"

# PHP Extensions
RUN docker-php-ext-install -j$(nproc) opcache pdo pdo_mysql
RUN pecl install xdebug-2.9.6
RUN docker-php-ext-enable xdebug
RUN echo "xdebug.remote_enable=1" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.remote_host=host.docker.internal" >> /usr/local/etc/php/php.ini
COPY conf/php.ini /usr/local/etc/php/conf.d/app.ini

# Apache
COPY conf/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite 
